#!/bin/bash

# This script should not print anything except percent_done to its stdout
# This is because this script's stdout is piped to yad --progress
# So, we direct all messages generated by pdftoppm to stderr , using 1>&2

# Number of files to convert (the +1 is to prevent overflow of >100%)
count=$(echo "$filelist" | wc -l)
count=$(($count+1))
#echo $count
# Remove trailing slashes in directory name
dest_dir="$(echo "$dest_dir" | sed 's/\/$//g')"
#echo "$filelist" 1>&2
ctr=0
#echo "Helper called" 1>&2
while read file ; do
    # Skip this round if $file is empty
    # BTW: how I miss C++'s continue and getline()
    #echo "$file" 1>&2
    if [ -n "$file" ] ; then
        file_name="$(basename "$file")"
        #echo "$file_name" 1>&2
        # Exit if pdftoppm doesn't exit successfully
        pdftoppm -jpeg "$file" "$dest_dir"/"$file_name" 1>&2 || echo 'pdftoppm encountered an error' >> "$dest_dir"/jpg2pdf.log
        # TODO: Make the file names prettier
        # find . -maxdepth 1 -name "$file".pdf"-*.jpg" | xargs -I{} mv {} "$(echo {} | sed 's/\.jpg$//' | sed 's/\.pdf-')" 1>&2
        ctr=$(($ctr+1))
        percent_done=$(((100*$ctr)/$count))
        echo $percent_done 
    fi
done < <(echo "$filelist")

exit 0
